### ISSUE TITLE
!bet 2 lose - Not given on lose

### ISSUE THREAD

**Issue by codeduction** [jasonp/botspade#12]
<etheco> !bet 2 lose
<botspade> etheco: Bet recorded.

<watchspade> !reportgame loss
<botspade> Bets tallied. 0 Spade Points won by 0 gambler(s).

**Comment by codeduction** [comment]
the issue is i cant spell, and its meant to be loss, Needs to check that the win/tie/loss is what is typed.

**Comment by jasonp** [comment]
Fixed and in codebase.
