### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by EightyNine** [jasonp/botspade#27]
SyntaxError: botspade.rb:538: invalid multibyte char (US-ASCII)

**Comment by jasonp** [comment]
It could be that there's an invalid apostrophe in the message. Try changing up the message in your local code and if it works, feel free to send a pull request?

I haven't touched the code in quite a while (obviously).

**Comment by EightyNine** [comment]
that happend too with a clean installation :(

**Comment by EightyNine** [comment]
ohh ok what ever. Use rvm use 2.1.0 again and everything is working :D
